module.exports = [
  "e probabilidade de tempestade forte, proteja-se!",
  "e probabilidade de tempestade tropical!",
  "e F U R A C Ã O, fudeeuu!",
  "e chances de tempestades severas! ⛈",
  "com tempestades. ⛈",
  "com misto de neve e chuva. 🌨",
  "com misto de chuva e gelo. 🌧",
  "com misto neve e gelo.",
  "com geada fina.",
  "e chance de alguns chuviscos! ☔️",
  "Congelamento chuva",
  "e chance de alguns chuviscos! ☔️",
  "e chance de alguns chuviscos! ☔️",
  "Neve baixa",
  "Tempestade com neve",
  "com ventania e neve!",
  "e neve! Carai frozi to bem não! ☃️ https://pbs.twimg.com/media/EM43B8jWoAE2seI.jpg",
  "e use um capacete, chance de chuva de granizo! ⛑",
  "Gelo",
  "e poeiraaaa, poeiraaaaa, poeira, levantou poeiraa! 🎵",
  "com neblina. 🌫",
  "Tempestade de areia",
  "Fumacento",
  "com vento acentuado! 💨",
  "com ventania. 💨",
  "e tempo frio. 🥶",
  "e tempo nublado. 🌥",
  "com tempo limpo, partiu praia! ☀️🏖",
  "e tempo nublado. 🌥",
  "com céu parcialmente nublado. 🌤",
  "com céu parcialmente nublado. 🌤",
  "com tempo limpo, partiu praia! ☀️🏖",
  "com sol descascando, lembre-se do protetor e dos óculos! 😎 ",
  "com céu estrelado. Aproveite pra se declarar pro mozão! 💘 [GATILHO]",
  "com céu ensolarado e muitas nuvens. 🌤",
  "com misto de chuva e granizo, tragam seus copos de whisky! 🥃🧊",
  "e ar quente! 🥵",
  "com tempestades isoladas! ⛈",
  "com trovoadas dispersas! 🌩",
  "com trovoadas dispersas! 🌩",
  "com chuvas esparsas.",
  "Pesados neve",
  "Chuviscos com neve",
  "Neve pesada",
  "e céu com sol e poucas nuvens. 🌤",
  "com chuva, não esqueça sua umbrella, ella, ella, eh, eh, eh! Under my umbrella, ella, ella, eh, eh, eh! ☔️",
  "Queda de neve",
  "com tempestades isoladas! ⛈",
  "Serviço não disponível",
];
